//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Web_ProjectEntities : DbContext
    {
        public Web_ProjectEntities()
            : base("name=Web_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<bookType> bookType { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderHistory> orderHistory { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<userType> userType { get; set; }
    }
}
