//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderHistory
    {
        public int ID { get; set; }
        public int orderID { get; set; }
        public int bookID { get; set; }
        public int quantity { get; set; }
        public int date { get; set; }
    
        public virtual book book { get; set; }
        public virtual order order { get; set; }
    }
}
